<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Third-Party Dependencies</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            margin: 40px;
            background: #f9fafb;
            color: #1f2937;
        }

        h1 {
            border-bottom: 3px solid #2563eb;
            padding-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background: white;
            box-shadow: 0 2px 10px rgba(0,0,0,0.06);
        }

        th {
            background: #2563eb;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }

        td {
            padding: 10px;
            border-bottom: 1px solid #e5e7eb;
        }

        tr:nth-child(even) {
            background: #f3f4f6;
        }

        code {
            background: #eef2ff;
            padding: 3px 6px;
            border-radius: 4px;
        }

        .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #6b7280;
        }
    </style>
</head>
<body>

<h1>📦 Third-Party Dependencies</h1>
<p><em>Generated on ${.now?string("yyyy-MM-dd")}</em></p>

<table>
    <tr>
        <th>Group ID</th>
        <th>Artifact ID</th>
        <th>Version</th>
        <th>License(s)</th>
    </tr>

<#assign seen = []>

<#list dependencyMap as entry>

    <#-- Clean dependency string -->
    <#assign clean = entry.key?replace("MavenProject: ", "")>
    <#assign clean = clean?split(" @")[0]>
    <#assign parts = clean?split(":")>

    <#if parts?size == 3>
        <#assign gav = parts[0] + ":" + parts[1] + ":" + parts[2]>

        <#if !seen?seq_contains(gav)>
            <#assign seen = seen + [gav]>
            <#assign licenseText = entry.value?join(", ")>

    <tr>
        <td><code>${parts[0]}</code></td>
        <td><strong>${parts[1]}</strong></td>
        <td>${parts[2]}</td>
        <td>${licenseText}</td>
    </tr>

        </#if>
    </#if>

</#list>

</table>

<div class="footer">
    Generated by license-maven-plugin 2.7.1
</div>

</body>
</html>