# 📦 Third-Party Dependencies

_Generated on ${.now?string("yyyy-MM-dd")}_

---

| Group ID | Artifact ID | Version | License(s) |
|:---------|:------------|:--------|:------------|
<#assign seen = []>
<#list dependencyMap as entry>
<#assign clean = entry.key?replace("MavenProject: ", "")>
<#assign clean = clean?split(" @")[0]>
<#assign parts = clean?split(":")>
<#if parts?size == 3>
<#assign gav = parts[0] + ":" + parts[1] + ":" + parts[2]>
<#if !seen?seq_contains(gav)>
<#assign seen = seen + [gav]>
<#assign licenseText = entry.value?join(", ")>
| `${parts[0]}` | **${parts[1]}** | ${parts[2]} | ${licenseText} |
</#if>
</#if>
</#list>

---

<sub>Generated by license-maven-plugin 2.7.1</sub>