{
 "title": "C2SIM System - Send C2SIM messages",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sharedsession",
    "label": "C2SIM Shared session",
    "query": {
     "query": "label_values(c2sim_client_msg_valid_count_total,c2sim_shared_session)"
    }
   },
   {
    "name": "systemname",
    "label": "System name",
    "query": {
     "query": "label_values(c2sim_client_msg_valid_count_total,c2sim_system_name)"
    }
   },
   {
    "name": "msgtype",
    "label": "C2SIM MSG TYPE",
    "query": {
     "query": "label_values(c2sim_client_msg_valid_count_total,c2sim_msg_kind)"
    }
   },
   {
    "name": "errorkind",
    "label": "Error kind",
    "query": {
     "query": "label_values(c2sim_client_msg_invalid_count_total,c2sim_error_kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "C2SIM Message size send by system '$systemname'",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(c2sim_client_msg_bytes_sent_total{c2sim_app=\"c2sim-server\", c2sim_shared_session=~\"$sharedsession\", c2sim_system_name=~\"$systemname\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  invalid C2SIM messages (${__from:date:YY-MM-DD HH:mm:ss} → ${__to:date:HH:mm:ss})",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(c2sim_client_msg_invalid_count_total{c2sim_app=\"c2sim-server\", c2sim_shared_session=~\"$sharedsession\", c2sim_system_name=~\"$systemname\", c2sim_error_kind=~\"$errorkind\"}[$__range])",
     "legendFormat": "ERROR {{ c2sim_error_kind }}"
    }
   ]
  },
  { "title": "Valid C2SIM messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "sharedsession" },
  {
   "title": "Total  valid C2SIM messages (${__from:date:YY-MM-DD HH:mm:ss} → ${__to:date:HH:mm:ss})",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(c2sim_client_msg_valid_count_total{c2sim_app=\"c2sim-server\", c2sim_shared_session=~\"$sharedsession\", c2sim_system_name=~\"$systemname\", c2sim_msg_kind=~\"$msgtype\"}[$__range])",
     "legendFormat": "MSG KIND {{ c2sim_msg_kind }}"
    }
   ]
  },
  {
   "title": "Valid C2SIM messages (per minute)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(c2sim_client_msg_valid_count_total{c2sim_app=\"c2sim-server\", c2sim_shared_session=~\"$sharedsession\", c2sim_system_name=~\"$systemname\", c2sim_msg_kind=~\"$msgtype\"}[1m]) * 60",
     "legendFormat": "MSG KIND {{ c2sim_msg_kind }}"
    }
   ]
  },
  {
   "title": "Invalid C2SIM messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "sharedsession",
   "collapsed": true
  }
 ]
}