{
 "title": "C2SIM-server endpoints",
 "description": "Statistics for RESTful endpoints on C2SIM server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "C2SIM endpoint",
    "query": {
     "query": "label_values(c2sim_request_duration_seconds_bucket,c2sim_request_endpoint)"
    }
   },
   {
    "name": "status",
    "label": "C2SIM Status",
    "query": {
     "query": "label_values(c2sim_request_duration_seconds_bucket,c2sim_request_status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of requests (per minute)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (c2sim_request_endpoint, c2sim_request_status) (\r\n  increase(\r\n    c2sim_request_duration_seconds_count{\r\n      c2sim_app=\"c2sim-server\",\r\n      c2sim_request_endpoint=~\"$endpoint\",\r\n      c2sim_request_status=~\"$status\"\r\n    }[1m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency (50%)",
   "type": "stat",
   "description": "50 percentile request latency by endpoint and status (5-minute window).",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le, c2sim_request_endpoint, c2sim_request_status) (\r\n    rate(\r\n      c2sim_request_duration_seconds_bucket{\r\n        c2sim_app=\"c2sim-server\",\r\n        c2sim_request_endpoint=~\"$endpoint\",\r\n        c2sim_request_status=~\"$status\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency (95%)",
   "type": "stat",
   "description": "95th percentile request latency by endpoint and status (5-minute window).",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le, c2sim_request_endpoint, c2sim_request_status) (\r\n    rate(\r\n      c2sim_request_duration_seconds_bucket{\r\n        c2sim_app=\"c2sim-server\",\r\n        c2sim_request_endpoint=~\"$endpoint\",\r\n        c2sim_request_status=~\"$status\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency (99%)",
   "type": "stat",
   "description": "99 percentile request latency by endpoint and status (5-minute window).",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le, c2sim_request_endpoint, c2sim_request_status) (\r\n    rate(\r\n      c2sim_request_duration_seconds_bucket{\r\n        c2sim_app=\"c2sim-server\",\r\n        c2sim_request_endpoint=~\"$endpoint\",\r\n        c2sim_request_status=~\"$status\"\r\n      }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  }
 ]
}