/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
 * 
 * @param code Unique C2SimError code to identify the C2SimError
 * @param message C2SimError message (English)
 * @param details Dictionary to add detail information to C2SimError object
 */
data class C2SimError(
    /* Unique C2SimError code to identify the C2SimError */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("code")
    val code: kotlin.String,
    /* C2SimError message (English) */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("message")
    val message: kotlin.String,
    /* Dictionary to add detail information to C2SimError object */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("details")
    val details: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null
)

