/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
* 
* Values: CREATED,UPDATED
*/
enum class CreateUpdateType(val value: kotlin.String) {

    CREATED("CREATED"),

    UPDATED("UPDATED");

}

