/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models

import org.c2sim.server.api.models.SessionInfo
import org.c2sim.server.api.models.StateType

/**
 * 
 * @param sessionName Unique ID. (RFC 3986)
 * @param createdAt Timestamp when the session was created.
 * @param info 
 * @param state 
 */
data class DynamicSessionInfo(
    /* Unique ID. (RFC 3986) */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("sessionName")
    val sessionName: kotlin.String,
    /* Timestamp when the session was created. */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("createdAt")
    val createdAt: java.time.OffsetDateTime,
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("info")
    val info: SessionInfo,
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("state")
    val state: StateType = StateType.UNINITIALIZED
)

