/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
 * Resign from session
 * @param reason Reason why resigned
 */
data class RequestResignSession(
    /* Reason why resigned */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("reason")
    val reason: kotlin.String? = null
)

