/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
 * 
 * @param clientIdDisplayName Human-readable C2SIM client identifier, doesn't have to be unique (only used for logging)
 * @param systemName The system name (this will be used when there is no auth info )
 */
data class RequestJoinSession(
    /* Human-readable C2SIM client identifier, doesn't have to be unique (only used for logging) */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("clientIdDisplayName")
    val clientIdDisplayName: kotlin.String,
    /* The system name (this will be used when there is no auth info ) */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("systemName")
    val systemName: kotlin.String? = null
)

