/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
 * 
 * @param msg Resign message
 */
data class ResponseResignSession(
    /* Resign message */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("msg")
    val msg: kotlin.String
)

