/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models

import org.c2sim.server.api.models.CreateUpdateType
import org.c2sim.server.api.models.DynamicSessionInfo

/**
 * 
 * @param creation 
 * @param session 
 */
data class ResponseCreateSession(
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("creation")
    val creation: CreateUpdateType,
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("session")
    val session: DynamicSessionInfo
)

