/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
 * 
 * @param trackingId Can be use to track send in message log
 */
data class ResponseSend(
    /* Can be use to track send in message log */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("trackingId")
    val trackingId: kotlin.String? = null
)

