/**
 * C2SIM Server interface specification
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3-3-2026
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.c2sim.server.api.models


/**
 * 
 * @param c2simSchemaVersion The XSD version of C2SIM schema used in session. All messages will be validated against this XSD schema.
 * @param displayName Small human readable name to identify the session
 * @param description Where the session is used for.
 */
data class SessionInfo(
    /* The XSD version of C2SIM schema used in session. All messages will be validated against this XSD schema. */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("c2simSchemaVersion")
    val c2simSchemaVersion: kotlin.String,
    /* Small human readable name to identify the session */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("displayName")
    val displayName: kotlin.String,
    /* Where the session is used for. */
    
    @field:com.fasterxml.jackson.annotation.JsonProperty("description")
    val description: kotlin.String
)

