name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile-c2sim-server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/c2sim-server:latest
          
          